Repository Stratejia/nextjs-graphql-example, pull requests merged in 2022-05, with the labels that each got.

#11 Add basic CI
  .github/workflows/build-frontend.yml
  .github/workflows/lint-general.yml
Labels: devops

#16 docs: add no return types style guide rule
  docs/style-guide.md
Labels: documentation

#17 docs: add type params style guide
  docs/style-guide.md
Labels: documentation

#21 docs: add documentation on if statements
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  docs/style-guide/typescript.md
Labels: documentation

#14 Add basic usage of styled components
  .husky/pre-commit
  frontend/components/common/layouts/Container.tsx
  frontend/components/common/layouts/Page.tsx
  frontend/components/common/layouts/index.ts
  frontend/components/common/typography/AppTitle.tsx
  frontend/components/common/typography/Body1.tsx
  frontend/components/common/typography/Typography.tsx
  frontend/components/common/typography/index.ts
  frontend/contexts/ThemeProvider.tsx
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/api/hello.ts
  frontend/pages/index.tsx
  frontend/styles/GlobalStyle.tsx
  frontend/styles/colors.ts
  frontend/styles/fonts.ts
  frontend/styles/globals.css
  frontend/styles/index.ts
  frontend/styles/spacing.ts
  frontend/types/styles.d.ts
  frontend/yarn.lock
Labels: feature

#30 improv: add storybook
  README.md
  docs/chosen-technologies.md
  docs/style-guide/styling.md
  docs/style-guide/typescript.md
  frontend/.eslintrc.js
  frontend/.storybook/contexts.js
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/README.md
  frontend/contexts/ThemeProvider.tsx
  frontend/package.json
  frontend/stories/components/common/layouts/Container.stories.tsx
  frontend/stories/components/common/layouts/Page.stories.tsx
  frontend/stories/components/typography/AppTitle.stories.tsx
  frontend/stories/components/typography/Body1.stories.tsx
  frontend/stories/pages/Home.stories.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: improvement

#37 feat: add support for i18n
  docs/architecture/frontend.md
  docs/chosen-technologies.md
  docs/development/components/index.md
  docs/development/index.md
  docs/index.md
  docs/references.md
  frontend/.storybook/contexts.js
  frontend/.storybook/i18n.js
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/README.md
  frontend/components/common/layouts/Container.stories.tsx
  frontend/components/common/layouts/Page.stories.tsx
  frontend/components/common/layouts/Page.tsx
  frontend/components/common/layouts/index.ts
  frontend/components/common/typography/AppTitle.stories.tsx
  frontend/components/common/typography/Body1.stories.tsx
  frontend/components/common/typography/index.ts
  frontend/contexts/ThemeProvider.tsx
  frontend/next-i18next.config.js
  frontend/next.config.js
  frontend/package.json
  frontend/pages/Home.stories.tsx
  frontend/pages/_app.page.tsx
  frontend/pages/index.page.tsx
  frontend/pages/index.tsx
  frontend/public/locales/en/common.json
  frontend/public/locales/en/home.json
  frontend/tsconfig.json
  frontend/types/i18n.d.ts
  frontend/utils/getServerSideTranslations.ts
  frontend/yarn.lock
  package.json
Labels: feature, improvement

#39 feat: add snapshot tests
  .github/workflows/build-frontend.yml
  docs/architecture/frontend.md
  docs/chosen-technologies.md
  docs/development/components/index.md
  docs/development/index.md
  docs/development/testing/general.md
  docs/development/testing/index.md
  docs/development/testing/unit-testing/general.md
  docs/development/testing/unit-testing/index.md
  docs/development/testing/unit-testing/mocking.md
  docs/development/testing/unit-testing/ui-components.md
  docs/development/ui-components/common/index.md
  docs/development/ui-components/common/layouts/Container.md
  docs/development/ui-components/common/layouts/Page.md
  docs/development/ui-components/common/layouts/index.md
  docs/development/ui-components/common/typography/AppTitle.md
  docs/development/ui-components/common/typography/Body1.md
  docs/development/ui-components/common/typography/index.md
  docs/development/ui-components/index.md
  docs/references.md
  docs/style-guide/index.md
  docs/style-guide/typescript.md
  frontend/.prettierignore
  frontend/.storybook/main.js
  frontend/README.md
  frontend/components/common/layouts/Container.stories.tsx
  frontend/components/common/layouts/__stories__/Container.stories.tsx
  frontend/components/common/layouts/__stories__/Page.stories.tsx
  frontend/components/common/layouts/__tests__/Container.test.tsx
  frontend/components/common/layouts/__tests__/Page.test.tsx
  frontend/components/common/layouts/__tests__/__snapshots__/Container.test.tsx.snap
  frontend/components/common/layouts/__tests__/__snapshots__/Page.test.tsx.snap
  frontend/components/common/typography/__stories__/AppTitle.stories.tsx
  frontend/components/common/typography/__stories__/Body1.stories.tsx
  frontend/components/common/typography/__tests__/AppTitle.test.tsx
  frontend/components/common/typography/__tests__/Body1.test.tsx
  frontend/components/common/typography/__tests__/__snapshots__/AppTitle.test.tsx.snap
  frontend/components/common/typography/__tests__/__snapshots__/Body1.test.tsx.snap
  frontend/contexts/__stubs__/ThemeProviderChild.tsx
  frontend/contexts/__tests__/ThemeProvider.test.tsx
  frontend/contexts/__tests__/__snapshots__/ThemeProvider.test.tsx.snap
  frontend/jest.config.js
  frontend/jest.setup.js
  frontend/package.json
  frontend/pages/__stories__/Home.stories.tsx
  frontend/pages/__tests__/Home.test.tsx
  frontend/pages/__tests__/__snapshots__/Home.test.tsx.snap
  frontend/pages/_app.page.tsx
  frontend/pages/index.page.tsx
  frontend/tsconfig.json
  frontend/tsconfig.test.json
  frontend/utils-test/withContexts.tsx
  frontend/utils/__tests__/getServerSideTranslations.test.ts
  frontend/yarn.lock
Labels: documentation, improvement

#44 docs: correct tests to fit documentation
  docs/development/testing/unit-testing/general.md
  docs/development/testing/unit-testing/mocking.md
  docs/style-guide/styling.md
  frontend/components/common/layouts/__stories__/Container.stories.tsx
  frontend/components/common/layouts/__tests__/Container.test.tsx
  frontend/components/common/layouts/__tests__/Page.test.tsx
  frontend/components/common/layouts/__tests__/__snapshots__/Container.test.tsx.snap
  frontend/components/common/layouts/__tests__/__snapshots__/Page.test.tsx.snap
  frontend/components/common/typography/__stories__/AppTitle.stories.tsx
  frontend/components/common/typography/__stories__/Body1.stories.tsx
  frontend/components/common/typography/__tests__/AppTitle.test.tsx
  frontend/components/common/typography/__tests__/Body1.test.tsx
  frontend/components/common/typography/__tests__/__snapshots__/AppTitle.test.tsx.snap
  frontend/components/common/typography/__tests__/__snapshots__/Body1.test.tsx.snap
  frontend/contexts/__tests__/ThemeProvider.test.tsx
  frontend/contexts/__tests__/__snapshots__/ThemeProvider.test.tsx.snap
  frontend/pages/__tests__/Home.test.tsx
  frontend/pages/__tests__/__snapshots__/Home.test.tsx.snap
  frontend/utils/__tests__/getServerSideTranslations.test.ts
Labels: improvement

#46 devops: build storybook in CI
  .github/workflows/build-frontend.yml
  .gitignore
Labels: devops

#50 chore: rename utils-tests folder
  docs/architecture/frontend.md
  docs/style-guide/typescript.md
  frontend/src/components/common/layouts/__tests__/Container.test.tsx
  frontend/src/components/common/layouts/__tests__/Page.test.tsx
  frontend/src/components/common/typography/__tests__/AppTitle.test.tsx
  frontend/src/components/common/typography/__tests__/Body1.test.tsx
  frontend/src/pages/__tests__/Home.test.tsx
  frontend/src/utils-tests/withContexts.tsx
  frontend/tsconfig.json
Labels: improvement

#53 feat: add full eslint config
  .eslintrc.base.js
  .github/workflows/build-frontend.yml
  .github/workflows/lint-general.yml
  .ls-lint.yml
  README.md
  docs/development/testing/general.md
  docs/style-guide/styling.md
  docs/style-guide/typescript.md
  frontend/.eslintrc.js
  frontend/.stylelintrc.js
  frontend/README.md
  frontend/package.json
  frontend/src/components/common/layouts/Container.tsx
  frontend/src/components/common/layouts/Page.tsx
  frontend/src/components/common/layouts/__stories__/Container.stories.tsx
  frontend/src/components/common/layouts/__stories__/Page.stories.tsx
  frontend/src/components/common/typography/AppTitle.tsx
  frontend/src/components/common/typography/Typography.tsx
  frontend/src/components/common/typography/__stories__/AppTitle.stories.tsx
  frontend/src/components/common/typography/__stories__/Body1.stories.tsx
  frontend/src/contexts/ThemeProvider.tsx
  frontend/src/contexts/__stubs__/ThemeProviderChild.tsx
  frontend/src/pages/api/hello.ts
  frontend/src/pages/index.page.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/styles/colors.ts
  frontend/src/styles/index.ts
  frontend/src/utils/__tests__/getServerSideTranslations.test.ts
  frontend/src/utils/getServerSideTranslations.ts
  frontend/yarn.lock
  package.json
  yarn.lock
Labels: improvement
